name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: go.mod
          fail_on_error: true
          filter_mode: nofilter
          golangci_lint_flags: --timeout=10m
  mod:
    name: Module Download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Module Download
        run: go mod download
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: go build -o ./sch-mes
      - uses: actions/upload-artifact@v4
        with:
          name: sch-mes
          path: ./sch-mes
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [mod, build]
    services:
      mariadb:
        image: mariadb:latest
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: SchMes
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run Test
        run: go test ./... -v
        env:
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_DATABASE: SchMes
          MARIADB_USERNAME: root
          MARIADB_PASSWORD: password
